name: horus_example_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.1
  # Bussines Logic Component
  #
  # Controller class to management the bloc state in the package
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6
  horusvision:
    path:
      ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
