name: horusvision
description: "The new era for show views, with that package you can show to your users any place of concert or airplane plane"
version: 0.1.1
package:
    git: https://github.com/dherediat97/HorusVision
    ref: main
homepage: https://github.com/dherediat97/HorusVision

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.0
  # Freezed - Model Smart Generation
  #
  # Utility to generate smart data-model classes in the package
  # https://pub.dev/packages/freezed
  freezed: ^2.5.2

  # Freezed - Model Smart Generation
  #
  # Annotations of Freezed package
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1

  # Json - Json Model Smart Generation
  #
  # Annotations to help freezed generate remote data-models classes
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  dio: ^5.0.0

  retrofit: ^4.1.0
  
  intl: ^0.19.0
  get_it: ^7.2.0
  lottie: ^3.1.2
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.2
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

  # Testing
  #
  # A mock framework inspired by Mockito
  # https://pub.dev/packages/mockito
  mockito: ^5.4.4

  # Utility Test library for Bloc 
  #
  # For test all of bloc lifecycle
  # https://pub.dev/packages/bloc_test
  bloc_test: ^9.1.7
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  generate: true
  assets: 
    - lib/assets/


flutter_intl:
  enabled: true
  class_name: AppLocalizations