name: horusvision
description: "The new era for show views, with that package you can show to your users any place of concert or airplane plane"
version: 0.0.2
package:
    git: https://github.com/dherediat97/HorusVision
    ref: main
homepage: https://github.com/dherediat97/HorusVision

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  go_router: ^14.2.0

  # Bussines Logic Component
  #
  # Controller class to management the bloc state in the package
  # https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.1.6

  # Freezed - Model Smart Generation
  #
  # Utility to generate smart data-model classes in the package
  # https://pub.dev/packages/freezed
  freezed: ^2.5.2

  # Freezed - Model Smart Generation
  #
  # Annotations of Freezed package
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1

  # Json - Json Model Smart Generation
  #
  # Annotations to help freezed generate remote data-models classes
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0

  dio: ^5.0.0

  retrofit: ^4.1.0
  
  intl: ^0.19.0
  get_it: ^7.2.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

  # Testing
  #
  # A mock framework inspired by Mockito
  # https://pub.dev/packages/mockito
  mockito: ^5.4.4

  # Utility Test library for Bloc 
  #
  # For test all of bloc lifecycle
  # https://pub.dev/packages/bloc_test
  bloc_test: ^9.1.7

flutter:
  generate: true
  assets: 
    - lib/assets/


flutter_intl:
  enabled: true
  class_name: AppLocalizations