name: horusvision
description: "The new era for show views, with that package you can show to your users any place of concert or airplane plane"
version: 0.0.2
package:
    git: https://github.com/dherediat97/HorusVision
    ref: main
homepage: https://github.com/dherediat97/HorusVision

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
