# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: dart run build_runner build --delete-conflicting-outputs    
      - name: Release example demo to the gh-pages web
        run: |
          cd example
          flutter build web --release -t lib/main.dart
          git config user.name dherediat97
          git config user.email dherediat97@gmail.com
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /HorusVision/
          customArgs: --dart-define="ENVIRONMENT=mock"

